name: Hello World Workflow

on: 
    push:
        branches: 
            - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello Shanki, this is your first GitHub Actions run!"
      - name: Say good bye
        run: |
          echo "bye the time is {uptime}"
          echo "Branch is ${{ github.ref }}" 

  greet_again:
    runs-on: ubuntu-latest
    steps:
        - name: see u next time
          run: |
           mkdir folder-test
           ls
           echo "Branch is ${{ github.ref }}" 
           echo "username ${{ github.actor }}" 
           echo "commit hash is ${{ github.sha }}" 
           echo "Repo is ${{ github.repository }}" 
