name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello Shanki, this is your first GitHub Actions run!"

      - name: Say Goodbye
        run: |
          echo "Uptime:"
          uptime
          echo "Branch is ${{ github.ref }}"

  greet_again:
    runs-on: ubuntu-latest

    env:
      MY_ENV: "Cloud Engineer"

    steps:
      - name: See you next time
        run: |
          mkdir folder-test
          ls
          echo "Branch is ${{ github.ref }}"
          echo "Username: ${{ github.actor }}"
          echo "Commit hash: ${{ github.sha }}"
          echo "Repo: ${{ github.repository }}"

      - name: Print my role
        run: echo "Shanki is a $MY_ENV"